#ifndef DOLL_DEF_VARIANT
# define DOLL_DEF_VARIANT(MacroName_, SymbolName_) /* */
# define DOLL_DEF_VARIANT_INTERNALLY_DEFINED_ 1
#endif

#undef  DOLL_VARIANT_RELEASE
#define DOLL_VARIANT_RELEASE     0
DOLL_DEF_VARIANT(RELEASE,        release)

#undef  DOLL_VARIANT_PROFILE
#define DOLL_VARIANT_PROFILE     1
DOLL_DEF_VARIANT(PROFILE,        profile)

#undef  DOLL_VARIANT_DEBUG
#define DOLL_VARIANT_DEBUG       2
DOLL_DEF_VARIANT(DEBUG,          debug)

#undef  DOLL_VARIANT_DEVELOPMENT
#define DOLL_VARIANT_DEVELOPMENT 3
DOLL_DEF_VARIANT(DEVELOPMENT,    development)

#ifdef DOLL_DEF_VARIANT_INTERNALLY_DEFINED_
# undef DOLL_DEF_VARIANT_INTERNALLY_DEFINED_
# undef DOLL_DEF_VARIANT
#endif
