#define AXASSERT_IMPLEMENTATION
#define   AXCONF_IMPLEMENTATION
#define  AXFIBER_IMPLEMENTATION
#define    AXLOG_IMPLEMENTATION
#define     AXMM_IMPLEMENTATION
#define AXPRINTF_IMPLEMENTATION
#define    AXSTR_IMPLEMENTATION
#define AXTHREAD_IMPLEMENTATION
#define   AXTIME_IMPLEMENTATION

#include "doll/AxlibConfig.h"

#include <axlib.hpp>
